version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: foodies-postgres
    environment:
      POSTGRES_USER: foodies
      POSTGRES_PASSWORD: foodiesfor2024
      POSTGRES_DB: foodiesdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
